UCR/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
| All Route Resources were created by using 'php artisan make:controller <ControllerName> --resource' command.
| Reason: These route controllers all have basic CRUD actions.
| See: https://laravel.com/docs/9.x/controllers (Resource Controllers) as best practice from Laravel
*/

Route::get('/', [App\Http\Controllers\MainController::class, 'main'])->name('main.home');

Route::resource('computers', 'App\Http\Controllers\DeviceController')->middleware(['auth', 'ucr']);

Route::get('rentals/manage',  [App\Http\Controllers\ManageRentalController::class, 'manage'])->name('rentals.manage');

Route::post('rentals/search', 'App\Http\Controllers\RentalController@search')->name('rentals.search');
Route::get('rentals/search/{brand}', 'App\Http\Controllers\RentalController@searchByBrand')->name('rentals.searchByBrand');
Route::get('rentals/rent/{id}', 'App\Http\Controllers\RentalController@rent')->middleware(['auth', 'customer'])->name('rentals.rent');
Route::resource('rentals', 'App\Http\Controllers\RentalController');

Route::resource('account', 'App\Http\Controllers\UserAccountController')->middleware('auth');

Auth::routes();

UCR/app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Device;
use App\Models\User;
use App\Models\UserRole;

class MainController extends Controller
{
    public function main()
    {
        $isUCRManager = false;
        $usersByRoles = null;
        $devicesByBrands = null;
        if(Auth::check())
        {
            $user = Auth::user();
            $isUCRManager = $user->isUCRManager();
            if($isUCRManager)
            {
                $usersByRoles = UserRole::where("name", "!=", "UCR_MANAGER")->withCount('users')->get();
                $devicesByBrands = Device::selectRaw('brand, count(*) as brand_count')->groupBy('brand')->get();
            }
        }
        return view('main', compact('isUCRManager', 'usersByRoles', 'devicesByBrands'));
    }
}

UCR/resources/views/layouts/manager/main.blade.php
<div class="row d-flex justify-content-center">
    <div class="col-md-8 bg-light mb-2">
        <div class="card">
            <div class="row card-body no-spacing">
            <h5 class="card-title text-center fw-bold pt-2"> Users By Groups Statistic </h5>
                @if($usersByRoles === null || count($usersByRoles) === 0)
                    <h7>There is no other user groups in the system yet.</h7>
                @else
                    <div class="row d-flex justify-content-center fw-bold">
                        <div class="col-md-8 ps-5">
                            <h7>User Group</h7>
                        </div>
                        <div class="col-md-4 text-center">
                            <h7>Total Users</h7>
                        </div>
                    </div>
                    <div class="row ps-4">
                        <hr>
                    </div>
                    @foreach ($usersByRoles as $usersByRole)
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-8 ps-5">
                                <label>{{ $usersByRole->name }}</label>
                            </div>
                            <div class="col-md-4 text-center">
                                <label>{{ $usersByRole->users_count }}</label>
                            </div>
                        </div>
                    @endforeach    
                @endif
            </div>
        </div>
    </div>    
</div>
<div class="row d-flex justify-content-center pt-5">
    <div class="col-md-8 bg-light mb-2">
        <div class="card">
            <div class="row card-body no-spacing">
            <h5 class="card-title text-center fw-bold pt-2"> Computers By Brands Statistic </h5>
                @if($devicesByBrands === null || count($devicesByBrands) === 0)
                    <h7>There is no other computers in the system yet.</h7>
                @else
                    <div class="row d-flex justify-content-center fw-bold">
                        <div class="col-md-8 ps-5">
                            <h7>Brand</h7>
                        </div>
                        <div class="col-md-4 text-center">
                            <h7>Total Computers</h7>
                        </div>
                    </div>
                    <div class="row ps-4">
                        <hr>
                    </div>
                    @foreach ($devicesByBrands as $devicesByBrand)
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-8 ps-5">
                                <label>{{ $devicesByBrand->brand }}</label>
                            </div>
                            <div class="col-md-4 text-center">
                                <label>{{ $devicesByBrand->brand_count }}</label>
                            </div>
                        </div>
                    @endforeach    
                @endif
            </div>
        </div>
    </div>    
</div>