UCR/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
| All Route Resources were created by using 'php artisan make:controller <ControllerName> --resource' command.
| Reason: These route controllers all have basic CRUD actions.
| See: https://laravel.com/docs/9.x/controllers (Resource Controllers) as best practice from Laravel
*/

Route::get('/', [App\Http\Controllers\MainController::class, 'main'])->name('main.home');

Route::resource('computers', 'App\Http\Controllers\DeviceController')->middleware(['auth', 'ucr']);

Route::get('rentals/manage',  [App\Http\Controllers\ManageRentalController::class, 'manage'])->name('rentals.manage');

Route::post('rentals/search', 'App\Http\Controllers\RentalController@search')->name('rentals.search');
Route::get('rentals/search/{brand}', 'App\Http\Controllers\RentalController@searchByBrand')->name('rentals.searchByBrand');
Route::get('rentals/rent/{id}', 'App\Http\Controllers\RentalController@rent')->middleware(['auth', 'customer'])->name('rentals.rent');
Route::resource('rentals', 'App\Http\Controllers\RentalController');

Route::resource('account', 'App\Http\Controllers\UserAccountController')->middleware('auth');

Auth::routes();

UCR/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
@include('layouts.head')
</head>
<body class="bg-light" style="overflow-x: hidden;">
    @include('layouts.header')
    
    <div class="container">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('jscript')
</body>
@include('layouts.footer')
</html>

UCR/resources/views/layouts/footer.blade.php
<footer class="text-center text-white" style="background-color: #163a5a;">
    <div class="container p-4 pb-0">
        <!-- UCR Social Media -->
        <section class="mb-4">
        <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/UniversityofTasmania/" role="button">
            <i class="bi bi-facebook"></i>
        </a>
        <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/universityoftasmania/?hl=en" role="button">
            <i class="bi bi-twitter"></i>
        </a>
        </section>
    </div>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-white">UCR - UTAS Computer Rental Services</a>
    </div>
    <!-- Copyright -->
</footer>

UCR/resources/views/layouts/head.blade.php
<meta http-equiv="Access-Control-Allow-Origin" content="*">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" crossorigin="anonymous">
<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/main.css') }}">
<link rel="stylesheet" href="{{ asset('css/form.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" crossorigin="anonymous"></script>
<title>UTAS Computer Rental Services</title>

UCR/resources/views/layouts/header.blade.php
@php
    // set it = true by default, as unauthenticated user can also see the Rental page
    $is_user_customer = true;
    $is_user_ucr = false;

    if (Auth::check())
    {
        $is_user_ucr = Auth::user()->isUCR();
        $is_user_customer = Auth::user()->isCustomer();
    }
    $brands = Config::get('computer.brands');
@endphp
<!-- Navigation Menu-->
<header>
    <div class="row" id="header">    
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" id="ucrindex" href="{{ route('main.home') }}"><label class="brand strong">UCR</label></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" 
                aria-controls="navbarMenu" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav me-auto">
                    @if($is_user_ucr)
                       <li class="nav-item">
                            <a class="nav-link {{request()->is('rentals', 'rentals/*') ? 'active' : ''}}" id="managerentalpage" href="{{ route('rentals.manage') }}">Manage Rental </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {{request()->is('computers', 'computers/*') ? 'active' : ''}}" id="computerpage" href="{{ route('computers.index') }}">Manage Computers </a>
                        </li>
                    @endif
                    
                        <li class="nav-item">
                            <a class="nav-link {{request()->is('rentals', 'rentals/*') ? 'active' : ''}}" id="rentalpage" href="{{ route('rentals.index') }}">Rent Computer</a>
                        </li>
                        @if(!Request::is('register') and !Request::is('login'))
                        <li class="nav-item">
                            <form id="search_devices" action="{{route('rentals.search')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                                <div class="input-group" style="padding-left: 50px;">
                                    <select class="form-control me-2 custom-select" name="brand">
                                        <option value="">Select Brand</option>
                                        @foreach($brands as $brand)
                                            <option value="{{$brand}}">{{ $brand }}</option>
                                        @endforeach
                                    </select>
                                    <div class="input-group-append">
                                        <input id="btnSearchDevices" type="submit" value="Search" class="btn btn-primary">
                                    </div>
                                </div>
                            </form>
                        </li>
                        @endif
                    
                    </ul>
                    
                    
                    <div class="d-flex" id="credentials">
                    @guest
                    @if(!Request::is('register') and !Request::is('login'))
                        <a href="{{ route('login') }}" class="btn btn-primary nav-item-button">Sign in</a>
                        <a href="{{ route('register') }}" class="btn btn-blue nav-item-button">Sign Up</a>
                    @endif
                    @else
                        <div class="dropdown pe-5">
                            <i class="bi bi-person-fill" id="myaccount"></i> {{ Auth::user()->f_name . ' ' . Auth::user()->l_name }}
                                <div class="dropdown-content">
                                  <a href="{{ route('account.index') }}">My Account</a>
                                  <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                        </div>
                    @endguest
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>