UCR/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
| All Route Resources were created by using 'php artisan make:controller <ControllerName> --resource' command.
| Reason: These route controllers all have basic CRUD actions.
| See: https://laravel.com/docs/9.x/controllers (Resource Controllers) as best practice from Laravel
*/

Route::get('/', [App\Http\Controllers\MainController::class, 'main'])->name('main.home');

Route::resource('computers', 'App\Http\Controllers\DeviceController')->middleware(['auth', 'ucr']);

Route::get('rentals/manage',  [App\Http\Controllers\ManageRentalController::class, 'manage'])->name('rentals.manage');

Route::post('rentals/search', 'App\Http\Controllers\RentalController@search')->name('rentals.search');
Route::get('rentals/search/{brand}', 'App\Http\Controllers\RentalController@searchByBrand')->name('rentals.searchByBrand');
Route::get('rentals/rent/{id}', 'App\Http\Controllers\RentalController@rent')->middleware(['auth', 'customer'])->name('rentals.rent');
Route::resource('rentals', 'App\Http\Controllers\RentalController');

Route::resource('account', 'App\Http\Controllers\UserAccountController')->middleware('auth');

Auth::routes();

UCR/app/Models/DeviceStatus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DeviceStatus extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    /**
    * @var array
    */
    protected $statuses = [
        'NEW', 
        'RENTED', 
        'RETURNED', 
        'MINOR DAMAGED', 
        'MAJOR DAMAGED', 
        'INACTIVE'
    ];

   /**
    * @param int $value
    * @return string|null
    */
    public function getDeviceStatusAttribute($value)
    {
        return Arr::get($this->statuses, $value);
    }
}

UCR/app/Models/Rental.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rental extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    /**
     * @return BelongsTo
     * @description get the device for the rental.
     */
    public function device()
    {
        return $this->belongsTo(Device::class, 'device_id');
    }
    
    
    /**
     * Get the User Who Rents
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'rented_by', 'id');
    }

    
    /**
     * Get the Rental Status of this rental
     */
    public function status()
    {
        return $this->belongsTo(RentalStatus::class, 'rental_status');
    }
}

UCR/app/Http/Controllers/RentalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use DB;
use Exception;
use Carbon\Carbon;
use App\Models\Device;
use App\Models\Rental;
use App\Models\RentalStatus;
use App\Models\DeviceStatus;
/**
 * For Customer to rent device
 */
class RentalController extends Controller
{

    public function __construct() {
        // Don't need to check if user login or not
        $this->middleware(['auth', 'customer'], ['except' => [
            'index', 'show', 'search', 'searchByBrand'
        ]]);
    }

    /**
     * Display a listing of available devices for rental.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $devices = Device::whereHas('device_statuses', function($q) {
            $q->whereIn('device_statuses.name', ['NEW', 'RETURNED']);
        })->get();
        return view('rentals/rental_computers', ['devices' => $devices]);
    }

    public function search(Request $request)
    {
        return $this->searchByBrand($request->brand);
    }

    public function searchByBrand($brand)
    {
        $devices = Device::whereRaw('brand = ?', $brand)->whereHas('device_statuses', function($q) {
            $q->whereIn('device_statuses.name', ['NEW', 'RETURNED']);
        })->get();
        return view('rentals/rental_computers', ['devices' => $devices]);
    }

    
    /**
     * Customer rents a device.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'hours' => 'required|numeric|min:1|max:5',
            'start_date' => 'required|date_format:Y-m-d|after_or_equal:today',
            'start_time' => 'required|date_format:H:i|after_or_equal:' . Carbon::now()->format('H:i'),
        ]);
        
        $input = $request->all();
        $device = Device::find($input['device_id']);
        /*
        * Calculating Price to pay for rent and do validation 
        */
        $deposit = Config::get('rental.deposit');
        $rent_per_hours = $input['hours'] * $device->rental_price;
        $min_price_to_pay = $deposit + $rent_per_hours;
        if(!empty($input['insurance']))
        {
            $insurance = Config::get('rental.insurance');
            $min_price_to_pay = $min_price_to_pay + $insurance;
        }
        $validator = $request->validate([
            'balance' => 'numeric|gte:' . $min_price_to_pay,
        ]);
        
        try 
        {
            $rental_status = RentalStatus::where('name', 'RENTED')->firstOrFail();
            $device_status = DeviceStatus::where('name', 'RENTED')->firstOrFail();
            DB::beginTransaction();
            $user = Auth::user();
            $account = $user->account;
            $updated_balance = 0;
            if($account !== null)
            {
                $updated_balance = $account->balance - $min_price_to_pay;
                $account->update([
                    'balance' => $updated_balance
                ]);
            }
            
            Rental::create([
                'start_date' => $input['start_date'] . ' ' . $input['start_time'] . ':00',
                'end_date' =>  $input['start_date'] . ' ' . $input['start_time'] . ':59',
                'rent_period' => $input['hours'],
                'rented_price' => $rent_per_hours,
                'insurance' => $insurance,
                'deposit' => $deposit,
                'rental_status' => $rental_status->id,
                'rented_by' => $user->id,
                'device_id' => $input['device_id']
            ]);

            $device->update([
                'status_id' => $device_status->id,
                'updated_by' => $user->id
            ]);

            DB::commit();
            return $this->index();
        } catch (Exception $e) {
            DB::rollBack();
            report($e);
            abort(500, 'Internal Server Error');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $device = Device::find($id);
        return view('computers/computer_details', compact('device'));
    }

    /**
     * For customers to see a rent page with Device's rental details
     * @param  int  $id Device Id to rent
     * @return \Illuminate\Http\Response
     */
    public function rent($id)
    {
        $device = Device::find($id);
        $user = Auth::user();
        $account = $user->account;
        return view('rentals/rent_computer', compact('device', 'account'));
    }
}

UCR/resources/views/rentals/manage_rentals.blade.php
@extends('layouts.app')

@section('content')
@php
    $brands = Config::get('computer.brands');
    $systems = Config::get('computer.systems');
@endphp
<div class="container" id="page">
    <main class="my-5" id="mainpage">
        <h2>&nbsp; Latest Rentals</h2>
        <hr>
        <div class="container">
            @if($devices === null || count($devices) === 0)
            <div class="row ps-2">
                <h5>There is no computers were rented</h5>
            </div>
            @else
            <div class="row">
                @foreach ($devices as $device)
                @php
                    $rental = $device->rental;
                @endphp
                <div class="col-md-12 bg-light mb-2">
                    <div class="card">
                        <div class="row card-body no-spacing">
                            <div class="col-md-2">
                                <img src="{{ asset($device->image_url) }}" class="img-fluid" style="max-height: 100px;">
                            </div>
                            <div class="col-md-4">
                                <h5 class="card-title text-center font-weight-bold">{{ $device->brand }}  - {{ $device->device_status->name }} </h5>
                                <div class="row no-spacing" style="display: flex; text-align: left;">
                                    <div class="col-md-7">
                                        <label style="width:100px"><b>Rented Price:</b></label>{{ $rental->rented_price}}$/Hour<br/>
                                        <label style="width:100px"><b>Deposit:</b></label>{{ empty($rental->deposit) ? "0" : $rental->deposit }}$ <br/>
                                    </div>
                                    <div class="col-md-5">
                                        <label style="width:55px"><b>Period:</b></label>{{ $rental->rent_period }}hr(s)<br/>
                                        <label style="width:55px"><b>By:</b></label>{{ $rental->user->l_name . ' ' . $rental->user->f_name }}  <br/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h5 class="card-title text-center font-weight-bold">Other Details</h5>
                                <div class="row no-spacing" style="display: flex; text-align: left;">
                                    <div class="col-md-6">
                                        <label style="width:55px"><b>Start:</b></label>{{ $rental->start_date }}<br/>
                                        <label style="width:55px"><b>End:</b></label>{{ $rental->end_date }}  <br/>
                                        <label style="width:55px"><b>Return:</b></label>{{ $rental->return_date }}  <br/>
                                    </div>
                                    <div class="col-md-6">
                                        <label style="width:70px"><b>Discount:</b></label>{{ empty($rental->discount) ? "0" : $rental->discount }}$<br/>
                                        <label style="width:70px"><b>Insurance:</b></label>{{ empty($rental->insurance) ? "0" : $rental->insurance }}$<br/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <!-- Pagination -->
            {{ $devices->links() }}
            @endif
        </div>
    </main>
</div>
@endsection

UCR/resources/views/rentals/rent_computer.blade.php
@extends('layouts.app')

@section('content')
@php
    $brands = Config::get('computer.brands');
    $systems = Config::get('computer.systems');
    $balance = empty($account->balance) ? 0 : $account->balance;
    $deposit = Config::get('rental.deposit');
    $insurance = Config::get('rental.insurance');
    $min_price_to_pay = $deposit + $device->rental_price;
    
@endphp
<div class="container" id="page">
    <main class="my-5" id="mainpage">
        <h2>&nbsp; Rent Computer </h2> 
        <hr>
        <div class="container">
            <form id="rentComputerFrm" action="{{route('rentals.store')}}" method="POST" enctype="multipart/form-data" class="needs-validation">
            @csrf
            <div class="row">
                <div class="col-md-7">
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-2"><label for="start_date">{{ __('Rent Date') }}</label></div>
                        <div class="col-md-4">
                            <input id="start_date" type="date" class="form-control @error('start_date') is-invalid @enderror" 
                            name="start_date" value="{{ old('start_date') }}" required autocomplete="start_date" autofocus
                            min="{{ date('Y-m-d') }}">

                            @error('start_date')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            
                        </div>
                        <div class="col-md-3"><label for="hours">{{ __('Hours') }}</label></div>
                        <div class="col-md-3">
                            <input id="hours" type="number" class="form-control @error('hours') is-invalid @enderror" 
                            name="hours" value="1" required autocomplete="hours" autofocus
                            min="1" max="5" step="0.5">

                            @error('hours')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Balance</div>
                        <div class="col-md-3">
                            <input id="balance" type="number" class="form-control @error('balance') is-invalid @enderror" 
                            name="balance" value="{{ $balance }}" readonly step="0.01">

                            @error('balance')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="row pt-1">
                <div class="col-md-7">
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-2"><label for="start_time">{{ __('Rent Time') }} </label></div>
                        <div class="col-md-4">
                            <input id="start_time" type="time" class="form-control @error('start_time') is-invalid @enderror" 
                            name="start_time" value="{{ old('start_time') }}" required autocomplete="start_time" autofocus
                            min="{{ date('H:i') }}">

                            @error('start_time')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            
                        </div>
                        
                        <div class="col-md-3">Insurance ({{ $insurance }}$)</div>
                        <div class="col-md-3">
                        <input type="checkbox" class="form-check-input" id="insurance" name="insurance" value="{{ $insurance }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Base Price</div>
                        <div class="col-md-3">
                            <input type="text" class="form-control" id="rental_price" name="rental_price" value="{{ $device->rental_price }}" disabled>
                        </div>
                    </div>
                    <div class="row justify-content-center d-flex align-items-center pt-1">
                        <div class="col-md-3">Deposit Fee</div>
                        <div class="col-md-3">
                            <input type="text" class="form-control" id="deposit" name="deposit" value="{{ $deposit }}" disabled>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="row ps-1 pt-3 justify-content-center d-flex align-items-center">
                <div class="col-md-3">
                <input type="hidden" name="device_id" value="{{ $device->id }}">
                    @if(!empty($account->balance) && $account->balance >= $min_price_to_pay )
                    <button type="submit" class="btn btn-primary float-right"> Submit </button>
                    @else
                    <span class="text-danger">You do not have sufficient balance to rent.</span>
                    @endif
                    <a class="btn btn-secondary" href="{{ route('rentals.index') }}">Cancel</a>
                </div>
            </div>
            </form>
        </div>
    </main>
</div>
@endsection

UCR/resources/views/rentals/rental_computers.blade.php
@extends('layouts.app')

@section('content')
@php
    $brands = Config::get('computer.brands');
    $systems = Config::get('computer.systems');
    $is_user_customer = false;
    if (Auth::check())
    {
        $is_user_customer = Auth::user()->isCustomer();
    }
@endphp
<div class="container" id="page">
    <main class="my-5" id="mainpage">
        <h2>&nbsp; Available Computers To Rent</h2>
        <hr>
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <div id="navbarSupportedContent" class="row collapse navbar-collapse">
                        <div class="col-md-12 d-flex justify-content-start">
                            <!-- Search form -->
                            <div class="row d-flex justify-content-start">
                                <div class="col-md-12 p5">
                                    @foreach($brands as $brand)
                                    <a class="btn btn-primary btn-small" href="{{route('rentals.searchByBrand',$brand)}}">{{ $brand }}</a>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>    
                </div>
            </nav>
            @if($devices === null || count($devices) === 0)
            <div class="row pt-3">
                <h5>There is no available computers for rent</h5>
            </div>
            @else
            @foreach ($devices->chunk(3) as $chunk)
            <div class="row">
                @foreach ($chunk as $device)        
                <div class="col-md-4 bg-light mb-2">
                    <div class="card">
                        <div class="row card-body no-spacing">
                            <div class="row">
                                <div class="col-md-5">
                                    <img src="{{ asset($device->image_url) }}" class="img-fluid" style="max-height: 200px;">
                                </div>
                                <div class="col-md-7">
                                    <h5 class="card-title text-center font-weight-bold">{{ $device->brand }} </h5>
                                    <div class="row no-spacing" style="display: flex; text-align: left;">
                                        <label style="width:70px"><b>Price:</b></label>{{ $device->rental_price }}$/Hour
                                    </div>
                                    <div class="row no-spacing" style="display: flex; text-align: left;">
                                        <label style="width:70px"><b>OS:</b></label>{{ $device->operating_system }}
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row pt-3 justify-content-center d-flex align-items-center">
                                @if($is_user_customer)
                                <div class="col-md-5">
                                    <a class="btn btn-primary btn-small" id="computerrent" href="{{route('rentals.rent',$device->id)}}">Rent Now</a>
                                </div>
                                @endif
                                <div class="col-md-5">
                                    <a class="btn btn-primary btn-small" id="computerdetails" href="{{route('rentals.show',$device->id)}}">View Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            @endforeach
            @endif
        </div>
    </main>
</div>
@endsection