UCR/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
| All Route Resources were created by using 'php artisan make:controller <ControllerName> --resource' command.
| Reason: These route controllers all have basic CRUD actions.
| See: https://laravel.com/docs/9.x/controllers (Resource Controllers) as best practice from Laravel
*/

Route::get('/', [App\Http\Controllers\MainController::class, 'main'])->name('main.home');

Route::resource('computers', 'App\Http\Controllers\DeviceController')->middleware(['auth', 'ucr']);

Route::get('rentals/manage',  [App\Http\Controllers\ManageRentalController::class, 'manage'])->name('rentals.manage');

Route::post('rentals/search', 'App\Http\Controllers\RentalController@search')->name('rentals.search');
Route::get('rentals/search/{brand}', 'App\Http\Controllers\RentalController@searchByBrand')->name('rentals.searchByBrand');
Route::get('rentals/rent/{id}', 'App\Http\Controllers\RentalController@rent')->middleware(['auth', 'customer'])->name('rentals.rent');
Route::resource('rentals', 'App\Http\Controllers\RentalController');

Route::resource('account', 'App\Http\Controllers\UserAccountController')->middleware('auth');

Auth::routes();

UCR/app/Models/DeviceStatus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DeviceStatus extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    /**
    * @var array
    */
    protected $statuses = [
        'NEW', 
        'RENTED', 
        'RETURNED', 
        'MINOR DAMAGED', 
        'MAJOR DAMAGED', 
        'INACTIVE'
    ];

   /**
    * @param int $value
    * @return string|null
    */
    public function getDeviceStatusAttribute($value)
    {
        return Arr::get($this->statuses, $value);
    }
}

UCR/resources/views/computers/computer.blade.php
@extends('layouts.app')

@section('content')
@php
    $brands = Config::get('computer.brands');
    $systems = Config::get('computer.systems');
    $title = 'New Device';
@endphp
<main class="mt-4 mb-5">
    <div class="container">
        <div class="row">
            <div class="row pt-1" id="warningDiv">
                <label id="warningLabel" class="text-danger"></label>
            </div>
        </div>
        @if(isset($device->id))
            @php
                $title = 'Edit Device';
            @endphp
            <form id="edit_computer" class="needs-validation" action="{{route('computers.update',$device->id)}}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
        @else
            <form id="add_computer" action="{{route('computers.store')}}" method="POST" enctype="multipart/form-data">
        @endif
            @csrf
            
            <div class="row">
                <div class="col-md-6 pe-4">
                    <h4 class="mb-4">{{ $title }}</h4>
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Brand</div>
                        <div class="col-md-9">
                            <select class="form-control" id="brand" name="brand" required>
                                <option value="">Select brand</option>
                                @foreach($brands as $br)
                                    <option value="{{$br}}" {{ (($device->brand === $br) || (old('brand') === $br)) ? 'selected' : ''}}>{{ $br }} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Rental Price / Hour</div>
                        <div class="col-md-9">
                            <input id="rental_price" type="number" min="1" step="0.01" inputmode="numeric" class="form-control @error('rental_price') is-invalid @enderror" name="rental_price" value="{{ empty($device->rental_price) ? old('rental_price') : $device->rental_price }}" required autocomplete="rental_price">
                            @error('rental_price')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>        
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Serial No.</div>
                        <div class="col-md-9">
                            <input id="serial_no" type="text" maxlength="20" class="form-control @error('serial_no') is-invalid @enderror" name="serial_no" value="{{ empty($device->serial_no) ? old('serial_no') : $device->serial_no }}" required autocomplete="serial_no">
                            @error('serial_no')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Short Description</div>
                        <div class="col-md-9">
                            <textarea name="description" maxlength="100" id="description" class="form-control" style="height: 134px;">{{ empty($device->description) ? old('description') : $device->description }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h4 class="mb-4">Other Details</h4>
                    <div class="row justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Operating System</div>
                        <div class="col-md-9">
                            <select class="form-control" id="operating_system" name="operating_system" required>
                                <option value="">Select OS</option>
                                @foreach($systems as $os)
                                    <option value="{{$os}}" {{ (($device->operating_system === $os) || (old('operating_system') === $os)) ? 'selected' : ''}}>{{ $os }} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row justify-content-center d-flex align-items-center pt-1">
                        <div class="col-md-3">Display Size</div>
                        <div class="col-md-9">
                            <input id="display_size" type="text" maxlength="20" class="form-control @error('display_size') is-invalid @enderror" name="display_size" value="{{ empty($device->display_size) ? old('display_size') : $device->display_size }}" required autocomplete="display_size">
                            @error('display_size')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">RAM</div>
                        <div class="col-md-9">
                            <input id="ram" type="text" maxlength="20" class="form-control @error('ram') is-invalid @enderror" name="ram" value="{{ empty($device->ram) ? old('ram') : $device->ram }}" required autocomplete="ram">
                            @error('ram')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">USB Ports</div>
                        <div class="col-md-9">
                            <input id="usb_ports" type="number" min="0" max="5" class="form-control @error('usb_ports') is-invalid @enderror" name="usb_ports" value="{{ empty($device->usb_ports) ? old('usb_ports') : $device->usb_ports }}" required autocomplete="usb_ports">
                            @error('usb_ports')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">HDMI Ports</div>
                        <div class="col-md-9">
                            <input id="hdmi_ports" type="number" min="0" max="5" class="form-control @error('hdmi_ports') is-invalid @enderror" name="hdmi_ports" value="{{ empty($device->hdmi_ports) ? old('hdmi_ports') : $device->hdmi_ports }}" required autocomplete="hdmi_ports">
                            @error('hdmi_ports')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row pt-1 justify-content-center d-flex align-items-center">
                        <div class="col-md-3">Image Path</div>
                        <div class="col-md-6">
                            <input id="image_url" type="file" class="form-control @error('image_url') is-invalid @enderror" name="image_url" max-file-size="2048" value="{{$device->image_url}}" {{ empty($device->image_url) ? 'required' : '' }} >
                            <span>(Max Size: 2mb)</span>
                            @error('image_url')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror

                        </div>
                        <div class="col-md-3">
                            @if(isset($device->image_url) && !empty($device->image_url))
                                <img src="{{ asset($device->image_url) }}" class="img-fluid" style="max-height: 150px;"></div>
                            @endif
                    </div>
                </div>
            </div>    
            <div class="row ps-1 pt-3">
                <div class="col-12 justify-content-center d-flex align-items-center">
                    <input type="hidden" id="id" name="id" value="{{ $device->id }}" />
                    <input id="btnSaveDevice" type="submit" value="Submit" class="btn btn-primary">&nbsp; 
                    <a class="btn btn-secondary" href="{{ route('computers.index') }}">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</main>
@endsection

UCR/resources/views/computers/computer_details.blade.php
@extends('layouts.app')

@section('content')
<main class="mt-4 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 pe-4">
            <h4 class="mb-4">Computer Details</h4>
                <div class="row justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Brand</div>
                    <div class="col-md-9">
                    {{$device->brand }}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Base Rental Price / Hour</div>
                    <div class="col-md-9">
                        {{$device->rental_price}}
                    </div>        
                </div>
                <div class="row pt-1">
                    <div class="col-md-8">
                        @if(isset($device->image_url))
                            <img src="{{ asset($device->image_url) }}" class="img-fluid" style="max-height: 150px;">
                        @endif
                    </div>    
                </div>
            </div>
            <div class="col-md-6">
                <h4 class="mb-4">Other Details</h4>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Serial No.</div>
                    <div class="col-md-9">
                        {{$device->serial_no}}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Operating System</div>
                    <div class="col-md-9">
                        {{ $device->operating_system }}
                    </div>
                </div>
                <div class="row justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Display Size</div>
                    <div class="col-md-9">
                        {{$device->display_size}}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">RAM</div>
                    <div class="col-md-9">
                        {{$device->ram}}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">USB Ports</div>
                    <div class="col-md-9">
                        {{$device->usb_ports}}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">HDMI Ports</div>
                    <div class="col-md-9">
                        {{$device->hdmi_ports}}
                    </div>
                </div>
                <div class="row pt-1 justify-content-center d-flex align-items-center">
                    <div class="col-md-3">Description</div>
                    <div class="col-md-9">
                        {{$device->description}}
                    </div>
                </div>
            </div>
            <div class="row ps-1 pt-3 justify-content-center">
                <a class="col-md-1 btn btn-secondary" href="{{ route('rentals.index') }}">Go Back</a>
            </div>
        </div>
    </div>
</main>
@endsection

UCR/resources/views/computers/computers.blade.php
@extends('layouts.app')

@section('content')
@php
    $is_user_manager = false;
    if (Auth::check())
    {
        $is_user_manager = Auth::user()->isUCRManager();
    }
@endphp
<div class="container" id="page">
    <main class="my-5" id="mainpage">
        <h2>&nbsp; Manage Computers</h2>
        <hr>
        <div class="container">
            @if($is_user_manager)
            <div class="col-md-3 d-flex">
                <a class="btn btn-primary btn-small" id="addComputer" href="{{route('computers.create')}}">Add New Computer</a>
            </div>
            @endif
            
            @if($devices === null || count($devices) === 0)
            <hr>
            <div class="row ps-2 pt-2">
                <h5>There is no computers</h5>
            </div>
            @else
            <div class="row pt-1">
                @foreach ($devices as $device)
                <div class="col-md-12 bg-light mb-2">
                    <div class="card">
                        <div class="row card-body no-spacing">
                            <div class="col-md-2">
                                <img src="{{ asset($device->image_url) }}" class="img-fluid" style="max-height: 150px;">
                            </div>
                            <div class="col-md-4">
                                <h5 class="card-title text-center font-weight-bold">{{ $device->brand }} - {{ $device->device_status->name }} </h5>
                                <div class="row no-spacing" style="display: flex; text-align: left;">
                                    <div class="col-md-7">
                                        <label style="width:50px"><b>Price:</b></label>{{ $device->rental_price }}$/Hour<br/>
                                        <label style="width:50px"><b>OS:</b></label>{{ $device->operating_system }} <br/>
                                    </div>
                                    <div class="col-md-5">
                                        <label style="width:55px"><b>Display:</b></label>{{ $device->display_size }}<br/>
                                        <label style="width:55px"><b>RAM:</b></label>{{ $device->ram }} <br/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <h5 class="card-title text-center font-weight-bold">Other Details</h5>
                                <div class="row no-spacing" style="display: flex; text-align: left;">
                                    <label style="width:60px"><b>S/N:</b></label>{{ $device->serial_no }}<br/>
                                    <label style="width:100px"><b>USB ports:</b></label>{{ $device->usb_ports }}<br/>
                                    <label style="width:100px"><b>HDMI ports:</b></label>{{ $device->hdmi_ports }}<br/>
                                </div>
                                <div class="row no-spacing justify-content-center">
                                    {{ $device->description }}
                                </div>
                            </div>
                            @if($device->device_status->name !== 'RENTED')
                            <div class="col-md-1 pt-1">
                                <div class="row ps-2">
                                    &nbsp;<a class="btn btn-primary btn-small" style="width: 60px;" id="computerdetails" href="{{route('computers.edit',$device->id)}}">Edit</a> <br/>
                                </div>
                                <div class="row pt-2">
                                    <form method="POST" action="{{route('computers.destroy',$device->id)}}">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                        
                                        <button type="submit" class="btn btn-danger btn-icon" style="width: 60px;" onclick="return confirm('Are you sure you want to delete this computer?')">
                                            <i class="bi bi-trash3-fill"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            @endif
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <!-- Pagination -->
            {{ $devices->links() }}
            @endif
        </div>
    </main>
</div>
@endsection